/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  

        
        GIVEUP("[action][GIVEUP]",1500),
        NEWGAME("[action][NEWGAME]",1500),
        ACCEPT("[action][ACCEPT]",1500),
        CLUE("[action][CLUE]",1500),
        BLUE("[action][BLUE]",2000),
        BROWN("[action][BROWN]",2000),
        GREEN("[action][GREEN]",2000),
        ORANGE("[action][ORANGE]",2000),
        RED("[action][RED]",2000);



private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
    
	return event;
}
@Override
public String getEvName(){
        
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
